---
title: "Contagion, networks, data, and software"
title-block-banner: assets/images/visualization.svg
title-block-banner-color: white
include-in-header:
  - text: |
      <style>
      .quarto-title-block .quarto-title-banner {
        background-position-y: center;
        height: 400px;
      }
      .title {
        background-color: rgba(0, 0, 0, 0.3); /* Adjust color and transparency as needed */
        padding: 10px; /* Add padding for spacing */
        display: inline-block; /* To only apply the background to the text */
        border-radius: 0px; /* Optional: adds rounded corners to the background */
      }
      </style>
toc: false
---

The Landry Lab at the University of Virginia studies **how the structure of networks and groups affect the spread of diseases, information, and ideology.**
We seek to answer questions like, How do groups change the way that contagion spreads?
How do groups form and fracture?
How can we use knowledge of the underlying structure of groups to effectively mitigate and optimize the spread of contagion?
We use tools from network science, mathematical modeling, Bayesian inference, and open-source development to help answer these questions.


::: {.column-page-inset .text-center}
```{=html}
<a class="btn btn-outline-dark", href="mailto:nicholas.landry@virginia.edu" target="_blank" rel="noopener noreferrer">
    <i class="ai bi-envelope" role='img' aria-label='Email'></i> Email
</a>
<a class="btn btn-outline-dark", href="https://github.com/landry-lab" target="_blank" rel="noopener noreferrer">
    <i class="bi bi-github" role='img' aria-label='Github'></i> Github
</a>
<br>
<br>
```
:::

## Open positions

We are recruiting the following positions:

* **Graduate Students**: Graduate students will have considerable latitude to choose courses and a research project that interests them. Reach out with any questions! See [here](pages/open_positions.qmd) for more information.
* **Undergraduate Students**: See [here](pages/open_positions.qmd) for more information.

We are always open to collaboration as well, so reach out if you're interested!

## Recent News

* **July 2026**: New preprint out! [Emergent contagion complexity: Disentangling mechanistic complexity from correlated heterogeneity](https://arxiv.org/abs/2607.25139) with [Katerina Tang](https://kbtang28.github.io/) (on the job market!), [Daniel Kaiser](https://kaiser-dan.github.io/), [William Thompson](https://www.willhwthompson.com/), [Jean-Gabriel Young](https://jgyoung.ca/), and [Laurent Hébert-Dufresne](https://laurenthebertdufresne.github.io/).
* **July 2026**: Prof. Landry gave a presentation on the [A Blue Start](https://doi.org/10.1038/s41597-026-06920-1) dataset at [IC2S2 2026](https://ic2s2-2026.org) in Burlington, VT!
* **July 2026**: Daniel Kaiser was at the [SIAM Annual Meeting](https://www.siam.org/conferences-events/siam-conferences/an26/) in Cleveland, presenting work on confounding between heterogeneous simple contagions.
* **June 2026**: The Landry Lab was at [NetSci 2026](https://www.netsci2026.com) in Boston! Daniel Kaiser presented a poster on information spreading on Bluesky, Abhay Gupta gave a talk on heterogeneous susceptibility and infectiousness on networks, and Prof. Landry gave a talk titled "Cartographic Characterization of Complex Contagions".
* **May 2026**: The lab was awarded a [SPARC Grant](https://research.as.virginia.edu/seed-funding) for the project "Understanding information diffusion on social media through the lens of ideological groups."
* **May 2026**: Paper accepted! "NotD: The network of the day" by Abhay, Jessica Taggart, and Prof. Landry accepted at Connections!
* **May 2026**: The lab was awarded a [Ralph E. Powe Junior Faculty Enhancement Award](https://www.orau.org/news/releases/2026/orau-awards-180k-in-research-grants-to-36-junior-faculty.html) for the project "Investigating how groups shape the diffusion of content on social media platforms."
* **May 2026**: New preprint out! [The nestedness of higher-order networks](https://arxiv.org/abs/2605.18420) by Timothy LaRock, Yanting Zhang, Jean-Gabriel Young, Nicole Eikmeier, Renaud Lambiotte, and Prof. Landry surveys and unifies different measures of higher-order inclusion structure.
* **May 2026**: New lab preprint out! [The interplay of network structure and correlated infectious traits in epidemic models](https://arxiv.org/abs/2605.12773) by Abhay and Prof. Landry. Check it out!
* **May 2026**: Prof. Landry gave a talk at the [Department of Genome Sciences](https://med.virginia.edu/genome-sciences/) annual retreat.
* **April 2026**: The Landry Lab hosted [Alyssa Smith](https://asmithh.github.io/) for a few days to talk about science!
* **April 2026**: ["A Blue Start: A large-scale pairwise and higher-order social network dataset"](https://doi.org/10.1038/s41597-026-06920-1) is now published in Scientific Data!
* **March 2026**: We have two new PhD candidates in the house! Congratulations, Andy Grieve and Ariana Craft!
* **March 2026**: New preprint posted! [Higher-order interactions at scientific conferences influence team formation](https://arxiv.org/abs/2603.02571) in collaboration with [Emma Zajdela](https://sites.northwestern.edu/emmazajdela/).
* **February 2026**: Tyler Long received a College Science Scholars stipend to support summer research in the Landry Lab. Congratulations, Tyler!
* **January 2026**: Michael Leonard rotates with the Landry Lab as a PhD student. Welcome, Michael!
* **December 2025**: New article published! [HIF: The hypergraph interchange format for higher-order networks](https://doi.org/10.1017/nws.2025.10018) out in Network Science!
* **November 2025**: Abhay has a new [paper](https://doi.org/10.1098/rspb.2025.1891) out! Congrats, Abhay!
* **November 2025**: Charlotte has a new [paper](https://doi.org/10.1002/ece3.72493) out! Congrats, Charlotte!
* **November 2025**: Prof. Landry gave a talk titled "A Practical Guide to Higher-Order Networks" at [Datapalooza](https://datascience.virginia.edu/pages/datapalooza)
* **October 2025**: Abhay, Andy, Charlotte, and Kuankuan were all at [SEPEEG 2025](https://sepeeg2025.blogspot.com)!
* **October 2025**: Prof. Landry wrote a news article with Laurent Hébert-Dufresne on doing group science with XGI. Read it [here](https://www.siam.org/publications/siam-news/articles/group-science-the-open-source-study-of-higher-order-networks-with-xgi/)!
* **September 2025**: New article published! [Stochastic diffusion with approximate master equations with mean-field limits](https://doi.org/10.1098/rsos.250726) out in Royal Society Open Science!

[Older news](news.qmd)