---
title: "Older news"
---

* **September 2025**: New article published! [Stochastic diffusion with approximate master equations with mean-field limits](https://doi.org/10.1098/rsos.250726) out in Royal Society Open Science!
* **August 2025**: Kuankuan Hu started her rotation in the Landry Lab as a PhD student.
* **August 2025**: Abhay Gupta joined the Landry Lab as a PhD student.
* **July 2025**: Ahmed presented a poster at the [Computing for Global Challenges (C4GC)](https://proceedings.biocomplexity.virginia.edu/institute/divisions/network-systems-science-and-advanced-computing/computing-global-challenges) poster session. Congrats, Ahmed!
* **June 2025**: Ahmed Ahmed joined the Landry Lab co-advised by [Baltazar Espinoza](https://scholar.google.com/citations?hl=en&user=ovg94mcAAAAJ) through the [Computing for Global Challenges (C4GC)](https://proceedings.biocomplexity.virginia.edu/institute/divisions/network-systems-science-and-advanced-computing/computing-global-challenges) summer internship program hosted by the Biocomplexity Institute. Welcome, Ahmed!
* **June 2025**: Prof. Landry attended [NetSci 2025](https://netsci2025.github.io) in Maastricht, NL, where he organized the [Software and Data for Supporting Network Science](https://netsci.nascol.net/) satellite workshop and presented work on sampling from the hypergraph configuration model.
* **May 2025**: New preprint on the arXiv! ["A Blue Start: A large-scale pairwise and higher-order social network dataset"](https://arxiv.org/abs/2505.11608) in collaboration with [Alyssa Smith](https://asmithh.github.io/), [Ilya Amburg](https://sites.google.com/site/ilyaamburg1/home), [Sagar Kumar](https://www.sagarkumar.net/), and [Brooke Foucault Welles](https://brooke-welles.squarespace.com/)!
* **May 2025**: The Landry Lab received a [Small Data Analytics Resource Award](https://www.rc.virginia.edu/service/dac/awards/) from the Data Analytics Center at UVA for the project titled "Analyzing large-scale social networks through the Bluesky social media platform".
* **May 2025**: "Governance as a complex, networked, democratic, satisfiability problem" is now published in [*npj Complexity*](https://doi.org/10.1038/s44260-025-00041-3)!
* **April 2025**: [Andy Grieve](https://www.linkedin.com/in/andrew-grieve-721718278/) was awarded an EXPAND fellowship to be co-advised by Prof. Landry (with primary advisor [Prof. Katja Kasimatis](https://bio.as.virginia.edu/people/katja-kasimatis)) to incorporate modeling into his research on sexual conflict and co-evolution. Congratulations, Andy!
* **April 2025**: [Charlotte Greene](https://www.linkedin.com/in/charlotte-greene-400a2a174/) was awarded an EXPAND fellowship to be co-advised by Prof. Landry (with primary advisor [Prof. Butch Brodie](https://bio.as.virginia.edu/people/edmund-d-brodie-iii)) to integrate network methods to phenotype aggression and quantify behavior. Congratulations, Charlotte!
* **April 2025**: Prof. Landry was an invited panelist at the [Social Contagions, Artificial Intelligence, and Democracy Workshop](https://contagion-science.virginia.edu/social-contagions-artificial-intelligence-and-democracy-workshop) at UVA.
* **March 2025**: [Abhay Gupta](https://bsky.app/profile/abhay-gupta.bsky.social) joining the Landry Lab in August 2025! Welcome, Abhay!
* **January 2025**: Prof. Landry is now a [courtesy faculty member](https://datascience.virginia.edu/people/nicholas-landry) in the School of Data Science! This will foster many exciting cross-school collaborations.
* **December 2024**: We have a new member joining the Landry Lab! [Daniel Kaiser](https://www.linkedin.com/in/daniel-kaiser-4a7b55139) will be joining us as a postdoc starting August 2025! Welcome, Daniel!
* **December 2024**: New [preprint](https://arxiv.org/abs/2412.03421) on the structure of effective governance is now posted!
* **October 2024**: The first publication for the Landry Lab is published in [Physical Review E](https://doi.org/10.1103/PhysRevE.110.L042301)!
* **August 2024**: The Landry Lab is established at the University of Virginia.