---
title: "Lab Norms"
---

## Lab culture

Some things that we are:

* Celebrating each others' successes
* Treating each other with respect

## Attendance

Our lab culture is collaborative and interactive. This primarily happens through talking and getting to know each other. Remote work can be very convenient and makes sense if you're sick, are traveling but not on vacation, and if you're just having one of those days :) I won't be looking over your shoulder (unless you need more structure, and do let me know if that's the case), but I generally have the expectation that you'll make an effort to be in the lab consistently.

## Graduation

My expectation for PhD students is to have at least 3 first-author papers published or posted to the ArXiv (or BioRxiv) by the time of graduation. Along the way, my hope is that you'll present your work at conferences and events at UVA and make professional connections whether that be in industry or academia.

## Authorship and mentorship

As a lab member, you will "own" at least one project and you can expect to be first author on that paper. It may be helpful to draw upon the expertise of other people in the lab (or external collaborators) over the course of a project, but I will always ask your permission before doing so. Being a first author comes with some expectations: you'll be expected to drive the project, generate results, contribute substantively to the methods and theory of the paper, and reach out when you need help.

I don't expect a PhD student to be able to write their first paper from scratch without any guidance along the way. Typically, I will offer a lot of guidance on the first paper with the theory, experiments, and writing, and then, for the subsequent two papers, I will give you more and more ownership. I will offer mentorship through weekly one-on-one meetings, lab meetings, and written feedback on code/writing.

You can expect me to write you a strong letter of recommendation for jobs applications and fellowships, just give me enough warning :) A month is a perfect amount of time, but at the end of the day, I want to help you succeed, so just ask!

## Collaboration

I think that collaborating across labs and even outside UVA is great for lab members! I do ask that core lab members let me know so that we can determine how it will impact your primary projects.

## Conferences

I am committed to sending core lab members to conferences once a year (it may be more, but definitely one). We have lab funding to cover this, but I will encourage applying for travel awards through UVA and other societies to help defray the cost of attendance.